#!/usr/bin/env node
/*
 * @Author: Kim
 * @Date: 2021-04-07 11:19:44
 * @LastEditTime: 2021-04-14 15:07:43
 * @LastEditors: Kim
 * @Description:
 * @FilePath: /template_react/bin
 */
const { execSync } = require("child_process");

const program = require("commander");
const package = require("./package.json");

program
    .version(package.version)
    .usage("./bin [options] <command>")
    .option("-i, --ip", "以ip启动项目")
    .option("-e, --env <env>", "启动环境", "t1")
    .option("-m, --mode <mode>", "打包模式", "prod")
    .option("-p, --port <port>", "启动端口号", 8002);

program.command("dev").description("开发模式").action(devCmd);
program.command("build").description("打包模式").action(buildCmd);
program.command("dll").description("打包dll文件").action(dllCmd);

program.parse(process.argv);

const options = program.opts();

const env = options.env;
const port = options.port;

function devCmd() {
    process.env.NODE_ENV = "dev";
    execSync("npm run dev", { stdio: "inherit" });
}

function buildCmd() {
    process.env.NODE_ENV = "prod";
    execSync("npm run build", { stdio: "inherit" });
}

function dllCmd() {
    process.env.NODE_ENV = program.mode;
    execSync("npm run build:dll", { stdio: "inherit" });
}

module.exports = {
    env,
    port,
};
